name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Darwin:

    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --parallel

  Linux:
    runs-on: [ubuntu-latest]
    container: swift:6.0.0
    steps:
      - uses: actions/checkout@v1
      - name: Linux
        run: swift test --parallel
